<?php

/**
 * @file
 * Contains welcome.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function welcome_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the welcome module.
    case 'help.page.welcome':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a welcome page.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function welcome_theme() {
  return [
    'welcome' => [
      'variables' => [
        'welcome_content' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_user_login().
 *
 * Redirect users to the welcome page on successful login.
 */
function welcome_user_login(AccountInterface $account) {
  $url = Url::fromRoute('welcome.welcome_home')->toString();

  // If there are no password reset parameters in the URL, then bypass the user
  // edit page and go straight to my-work.
  if (\Drupal::service('current_route_match')->getRouteName() !== 'user.reset.login') {
    return \Drupal::requestStack()->getCurrentRequest()->query->set('destination', $url);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * If a user logs in with a password reset, send them to the user edit form to
 * reset their password first, then redirect to my-work.
 */
function welcome_form_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = '_welcome_user_redirect';
}

/**
 * Custom submit handler to redirect users to welcome page.
 */
function _welcome_user_redirect(&$form, FormStateInterface $form_state) {
  // Redirect from user form on save only when user first logs in.
  if (\Drupal::request()->query->has('pass-reset-token')) {
    $form_state->setRedirect('welcome.welcome_home');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function welcome_preprocess_html(&$variables) {
  $current_route = \Drupal::routeMatch()->getRouteName();

  if ($current_route == 'welcome.welcome_home') {
    $variables['attributes']['class'][] = 'welcome-home';
  }
}

/**
 * Implements hook_page_attachments().
 */
function welcome_page_attachments(array &$page) {
  if (\Drupal::service('current_route_match')->getRouteName() == 'welcome.welcome_home') {
    $page['#attached']['library'][] = 'welcome/welcome.styles';
  }
}
