support_agency_name: 'Drupal Community'
knowledgebase_url: 'https://www.drupal.org/documentation'
request_support_url: 'https://www.drupal.org/support'
_core:
  default_config_hash: PddzJAR26TweqXbBlu6Cw9JBYQYDiAGd8ISQuoGP39w
