<?php

/**
 * @file
 * Contains fr_add_content.module.
 */

use Drupal\Component\Utility\Xss;

/**
 * Implements hook_theme().
 */
function fr_add_content_theme($existing, $type, $theme, $path) {
  return [
    'first_run__node_add_list' => [
      'template' => 'first-run--node-add-list',
      'base hook' => 'node_add_list',
    ],
    'first_run__page__node__add' => [
      'template' => 'first-run--page--node--add',
      'render-element' => 'page',
      'base hook' => 'page',
    ],
  ];
}

/**
 * Add custom theme template.
 */
function fr_add_content_theme_suggestions_node_add_list_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'first_run__node_add_list';
}

/**
 * Add custom theme template.
 */
function fr_add_content_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'node.add_page') {
    $suggestions[] = 'first_run__page__node__add';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function fr_add_content_preprocess_page(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'node.add_page') {
    $config = \Drupal::configFactory()->get('fr_add_content.settings');
    $intro_text = $config->get('intro_text');

    $variables['page']['fr_content']['intro_text'] = [
      '#markup' => Xss::filterAdmin($intro_text),
      '#type' => 'container',
      '#attributes' => [
        'class' => [
          'add-content-intro-text',
        ],
      ],
    ];
  }
}
